#!/usr/bin/env python3

import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

OUT_DIR = ROOT / "results" / "l4_automation_audit_ledger"
DOC_DIR = ROOT / "docs" / "l4" / "automation_audit_ledger"
PDF_DIR = ROOT / "results" / "l4_report_pdf"

OUT_DIR.mkdir(parents=True, exist_ok=True)
DOC_DIR.mkdir(parents=True, exist_ok=True)
PDF_DIR.mkdir(parents=True, exist_ok=True)

LEDGER_JSON = OUT_DIR / "automation_audit_ledger.json"
LEDGER_JSONL = OUT_DIR / "automation_audit_ledger.jsonl"
LEDGER_CSV = OUT_DIR / "automation_audit_manifest.csv"
LEDGER_MD = DOC_DIR / "AUTOMATION_AUDIT_LEDGER.md"
LEDGER_PDF = PDF_DIR / "zktrustllm_l4_automation_audit_ledger_steps96_100.pdf"

ARTIFACTS = [
    {
        "step": "Step 96",
        "component": "Agentic automation suite",
        "path": "results/l4_agentic_automation/agentic_automation_summary.json",
        "meaning": "Full automation-suite execution summary.",
    },
    {
        "step": "Step 96",
        "component": "Agentic automation manifest",
        "path": "results/l4_agentic_automation/agentic_automation_artifact_manifest.csv",
        "meaning": "Artifact manifest generated by the automation suite.",
    },
    {
        "step": "Step 97",
        "component": "Closed-loop KPI decision agent",
        "path": "results/l4_closed_loop_agent/closed_loop_kpi_decision.json",
        "meaning": "KPI-driven next-action decision evidence.",
    },
    {
        "step": "Step 97",
        "component": "Closed-loop KPI decision report",
        "path": "results/l4_closed_loop_agent/closed_loop_kpi_decision.md",
        "meaning": "Human-readable KPI decision report.",
    },
    {
        "step": "Step 98",
        "component": "Closed-loop remediation executor",
        "path": "results/l4_remediation_executor/remediation_execution_plan.json",
        "meaning": "Approved remediation execution plan.",
    },
    {
        "step": "Step 98",
        "component": "Closed-loop remediation report",
        "path": "results/l4_remediation_executor/remediation_execution_plan.md",
        "meaning": "Human-readable remediation execution record.",
    },
    {
        "step": "Step 99",
        "component": "Automation governance dashboard",
        "path": "results/l4_automation_governance/automation_governance_dashboard.json",
        "meaning": "Governance dashboard machine-readable evidence.",
    },
    {
        "step": "Step 99",
        "component": "Automation governance report",
        "path": "docs/l4/automation_governance/L4_AUTOMATION_GOVERNANCE_DASHBOARD.md",
        "meaning": "Supervisor-readable governance report.",
    },
    {
        "step": "Step 100",
        "component": "Automation policy",
        "path": "configs/l4_automation_policy.json",
        "meaning": "Explicit policy governing automatic, approval-gated, and forbidden actions.",
    },
    {
        "step": "Step 100",
        "component": "Policy-gated scheduler",
        "path": "results/l4_policy_scheduler/policy_scheduler_summary.json",
        "meaning": "Policy-gated scheduler execution summary.",
    },
    {
        "step": "Step 100",
        "component": "Policy-gated scheduler report",
        "path": "results/l4_policy_scheduler/policy_scheduler_summary.md",
        "meaning": "Human-readable scheduler report.",
    },
    {
        "step": "Step 100",
        "component": "Rollback note",
        "path": "results/l4_policy_scheduler/policy_scheduler_rollback_note.md",
        "meaning": "Recovery and rollback guidance.",
    },
    {
        "step": "Supervisor report",
        "component": "Full technical documentation PDF",
        "path": "results/l4_report_pdf/zktrustllm_l4_full_technical_documentation_steps77_93.pdf",
        "meaning": "Supervisor-ready full technical documentation.",
    },
    {
        "step": "Supervisor report",
        "component": "Governance dashboard PDF",
        "path": "results/l4_report_pdf/zktrustllm_l4_automation_governance_dashboard_steps96_98.pdf",
        "meaning": "Supervisor-ready automation governance dashboard.",
    },
]

def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def sha256_json(obj) -> str:
    payload = json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def read_json_if_possible(path: Path):
    if not path.exists() or path.suffix.lower() != ".json":
        return None
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def extract_status(path: Path):
    data = read_json_if_possible(path)
    if not isinstance(data, dict):
        return "N/A"

    if "overallStatus" in data:
        return str(data["overallStatus"])

    if "status" in data:
        return str(data["status"])

    if "decision" in data and isinstance(data["decision"], dict):
        return str(data["decision"].get("primaryAction", "DECISION_PRESENT"))

    if "primaryAction" in data:
        return str(data["primaryAction"])

    return "JSON_PRESENT"


def build_ledger():
    created_at = datetime.now(timezone.utc).isoformat()
    previous_hash = "GENESIS"
    entries = []

    for index, item in enumerate(ARTIFACTS, start=1):
        artifact_path = ROOT / item["path"]
        exists = artifact_path.exists()

        entry = {
            "index": index,
            "createdAt": created_at,
            "step": item["step"],
            "component": item["component"],
            "path": item["path"],
            "exists": exists,
            "sizeBytes": artifact_path.stat().st_size if exists else 0,
            "sha256": sha256_file(artifact_path) if exists else None,
            "statusOrDecision": extract_status(artifact_path) if exists else "MISSING",
            "meaning": item["meaning"],
            "previousEntryHash": previous_hash,
        }

        entry["entryHash"] = sha256_json(entry)
        previous_hash = entry["entryHash"]
        entries.append(entry)

    ledger = {
        "experiment": "step101_hash_chained_automation_audit_ledger",
        "createdAt": created_at,
        "purpose": "Create a tamper-evident hash-chained audit ledger for the L4 closed-loop automation pipeline.",
        "coverage": "Steps 96-100 plus supervisor-facing report artifacts.",
        "entryCount": len(entries),
        "missingArtifacts": [e["path"] for e in entries if not e["exists"]],
        "genesisHash": "GENESIS",
        "finalLedgerHash": previous_hash,
        "entries": entries,
        "files": {
            "ledgerJson": rel(LEDGER_JSON),
            "ledgerJsonl": rel(LEDGER_JSONL),
            "ledgerCsv": rel(LEDGER_CSV),
            "ledgerMarkdown": rel(LEDGER_MD),
            "ledgerPdf": rel(LEDGER_PDF),
        },
    }

    return ledger


def write_json_outputs(ledger):
    LEDGER_JSON.write_text(json.dumps(ledger, indent=2))

    with LEDGER_JSONL.open("w") as f:
        for entry in ledger["entries"]:
            f.write(json.dumps(entry, sort_keys=True) + "\n")

    with LEDGER_CSV.open("w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "index",
                "step",
                "component",
                "path",
                "exists",
                "sizeBytes",
                "sha256",
                "statusOrDecision",
                "previousEntryHash",
                "entryHash",
            ],
        )
        writer.writeheader()
        for entry in ledger["entries"]:
            writer.writerow({k: entry.get(k) for k in writer.fieldnames})

def write_markdown(ledger):
    lines = [
        "# Step 101 Hash-Chained Automation Audit Ledger",
        "",
        "## Purpose",
        "",
        "This report creates a tamper-evident audit ledger for the Level 4 closed-loop automation workflow.",
        "",
        "It records key artifacts from Steps 96-100, computes SHA-256 hashes, and links each entry through a hash chain.",
        "",
        "## Ledger Summary",
        "",
        f"- Created at: `{ledger['createdAt']}`",
        f"- Entry count: `{ledger['entryCount']}`",
        f"- Final ledger hash: `{ledger['finalLedgerHash']}`",
        f"- Missing artifacts: `{len(ledger['missingArtifacts'])}`",
        "",
        "## Research Meaning",
        "",
        "Step 101 strengthens the scientific auditability of the project. The automation workflow can now be inspected using a cryptographic provenance ledger rather than relying only on informal logs.",
        "",
        "This is important for the PhD milestone because it connects agentic automation, KPI decision making, remediation, scheduler governance, and supervisor reports into one verifiable evidence chain.",
        "",
        "## Audit Entries",
        "",
        "| # | Step | Component | Exists | Status / Decision | SHA-256 short | Entry hash short |",
        "|---:|---|---|---:|---|---|---|",
    ]

    for entry in ledger["entries"]:
        sha_short = entry["sha256"][:12] if entry["sha256"] else "MISSING"
        entry_short = entry["entryHash"][:12]
        lines.append(
            f"| {entry['index']} | {entry['step']} | {entry['component']} | "
            f"{entry['exists']} | {entry['statusOrDecision']} | {sha_short} | {entry_short} |"
        )

    lines.extend(
        [
            "",
            "## Governance Boundary",
            "",
            "This ledger does not modify experiments, run privileged commands, push code, deploy systems, or submit papers.",
            "",
            "It only records and verifies evidence artifacts that already exist in the project.",
            "",
            "## Generated Files",
            "",
            f"- Ledger JSON: `{ledger['files']['ledgerJson']}`",
            f"- Ledger JSONL: `{ledger['files']['ledgerJsonl']}`",
            f"- Ledger CSV: `{ledger['files']['ledgerCsv']}`",
            f"- Ledger Markdown: `{ledger['files']['ledgerMarkdown']}`",
            f"- Ledger PDF: `{ledger['files']['ledgerPdf']}`",
        ]
    )

    LEDGER_MD.write_text("\n".join(lines) + "\n")


def write_pdf(ledger):
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    except Exception as exc:
        print(f"PDF generation skipped because reportlab is unavailable: {exc}")
        return

    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "TitleCenter",
        parent=styles["Title"],
        alignment=1,
        fontSize=16,
        leading=20,
        spaceAfter=12,
    )

    body = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=9,
        leading=12,
        spaceAfter=8,
    )

    doc = SimpleDocTemplate(
        str(LEDGER_PDF),
        pagesize=A4,
        rightMargin=0.55 * inch,
        leftMargin=0.55 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.55 * inch,
    )

    story = [
        Paragraph("Step 101 Hash-Chained Automation Audit Ledger", title),
        Paragraph("ZKTrustLLM-Agents Level 4", styles["Heading2"]),
        Paragraph(
            "This PDF records the hash-chained audit ledger for the closed-loop automation workflow covering Steps 96-100.",
            body,
        ),
        Paragraph(f"Created at: {ledger['createdAt']}", body),
        Paragraph(f"Final ledger hash: {ledger['finalLedgerHash']}", body),
        Spacer(1, 10),
    ]

    table_data = [["#", "Step", "Component", "Exists", "Status", "SHA-256 short", "Entry hash short"]]

    for entry in ledger["entries"]:
        table_data.append(
            [
                entry["index"],
                entry["step"],
                entry["component"],
                str(entry["exists"]),
                entry["statusOrDecision"],
                entry["sha256"][:12] if entry["sha256"] else "MISSING",
                entry["entryHash"][:12],
            ]
        )

    table = Table(table_data, repeatRows=1, colWidths=[0.3 * inch, 0.75 * inch, 1.7 * inch, 0.45 * inch, 1.05 * inch, 0.9 * inch, 0.9 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 7),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    story.append(table)
    story.append(Spacer(1, 10))
    story.append(
        Paragraph(
            "Governance boundary: this ledger is read-only. It records evidence and does not push code, deploy systems, submit papers, delete evidence, or run privileged commands.",
            body,
        )
    )

    doc.build(story)


def main():
    ledger = build_ledger()
    write_json_outputs(ledger)
    write_markdown(ledger)
    write_pdf(ledger)

    print(json.dumps({
        "experiment": ledger["experiment"],
        "entryCount": ledger["entryCount"],
        "missingArtifacts": len(ledger["missingArtifacts"]),
        "finalLedgerHash": ledger["finalLedgerHash"],
        "ledgerJson": ledger["files"]["ledgerJson"],
        "ledgerMarkdown": ledger["files"]["ledgerMarkdown"],
        "ledgerPdf": ledger["files"]["ledgerPdf"],
    }, indent=2))


if __name__ == "__main__":
    main()
